title: PMLCourse
description: Princiles of Machine Learning, 2025 
theme: just-the-docs
search_enabled: true

# Navigation order
nav_order: 1

# Sidebar settings
nav:
  - title: Home
    url: /
    nav_order: 1
  - title: About
    url: /about
    nav_order: 2
  - title: Installation
    url: /installation
    nav_order: 3
