title: PMLCourse
description: Princiles of Machine Learning, 2025 
remote_theme: just-the-docs/just-the-docs
search_enabled: true


nav_order: 1  # Controls sidebar order

nav:
  - title: Home
    url: /home
    nav_order: 1
  - title: Syllabus
    url: /syllabus
    nav_order: 2
  - title: Resources
    url: /resources
    nav_order: 3
  - title: Assignments
    url: /assignments
    nav_order: 4
  - title: Staff
    url: /staff
    nav_order: 5
  - title: FAQ
    url: /faq
    nav_order: 6


# Color customization
color_scheme: light  # Options: light, dark

logo: "/logo.png"


footer_content: "© 2025 My Documentation Site. All rights reserved."


